Implementing CR feedback

diff --git a/.github/workflows/pr-staging-main-only.yml b/.github/workflows/pr-staging-main-only.yml
--- a/.github/workflows/pr-staging-main-only.yml
+++ b/.github/workflows/pr-staging-main-only.yml
@@ -3,14 +3,14 @@ name: 'Only branch staging can merge to branch main'
 run-name: ${{ github.actor }} is running PR staging to main check
 
 on:
-  pull_request:
+    pull_request:
 
 jobs:
-  check_branch:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check branch
-        if: github.base_ref == 'main' && github.head_ref != 'staging'
-        run: |
-          echo "ERROR: You can only merge to main from staging. All changes must go through staging."
-          exit 1
+    check_branch:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Check branch
+              if: github.base_ref == 'main' && github.head_ref != 'staging'
+              run: |
+                  echo "ERROR: You can only merge to main from staging. All changes must go through staging."
+                  exit 1
